"use client";
import { FormEvent, useState } from "react";
import { supabaseBrowser, syntheticEmail } from "@/lib/supabase";

export function AuthScreen({ onDone }: { onDone: () => void }) {
  const [mode,setMode]=useState<"login"|"register">("login"); const [role,setRole]=useState<"senior"|"family">("senior");
  const [error,setError]=useState(""); const [code,setCode]=useState(""); const [loading,setLoading]=useState(false);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError("");const fd=new FormData(e.currentTarget);const phone=String(fd.get("phone"));const password=String(fd.get("password"));
    if(mode==="register"){const res=await fetch("/api/register",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({role,phone,password,firstName:fd.get("firstName"),lastName:fd.get("lastName"),familyPhone:fd.get("familyPhone")})});const json=await res.json();if(!res.ok){setError(json.message);setLoading(false);return}if(json.connectionCode)setCode(json.connectionCode)}
    const {error:authError}=await supabaseBrowser().auth.signInWithPassword({email:syntheticEmail(phone),password});if(authError)setError("شماره موبایل یا رمز اشتباه است.");else onDone();setLoading(false)}
  if(code)return <main className="shell"><section className="card stack" style={{textAlign:"center",marginTop:80}}><h1>ثبت‌نام انجام شد</h1><p className="muted">این کد را دستی برای عضو خانواده بفرستید.</p><div style={{fontSize:42,fontWeight:900,letterSpacing:8,color:"#1769d2"}}>{code}</div><button className="btn" onClick={onDone}>ورود به برنامه</button></section></main>;
  return <main className="shell"><header style={{textAlign:"center",margin:"30px 0"}}><div className="brand">هملی</div><p className="muted">ارتباط ساده، خیال آسوده</p></header><section className="card stack"><div className="tabs"><button className={`tab ${mode==="login"?"active":""}`} onClick={()=>setMode("login")}>ورود</button><button className={`tab ${mode==="register"?"active":""}`} onClick={()=>setMode("register")}>ثبت‌نام</button></div>{mode==="register"&&<div className="grid2"><button className={`btn ${role!=="senior"?"secondary":""}`} onClick={()=>setRole("senior")}>سالمند</button><button className={`btn ${role!=="family"?"secondary":""}`} onClick={()=>setRole("family")}>خانواده</button></div>}<form className="stack" onSubmit={submit}>{mode==="register"&&<div className="grid2"><label className="label">نام<input className="input" name="firstName" required/></label><label className="label">نام خانوادگی<input className="input" name="lastName" required/></label></div>}<label className="label">شماره موبایل<input className="input" name="phone" inputMode="numeric" pattern="09[0-9]{9}" required/></label>{mode==="register"&&role==="senior"&&<label className="label">شماره عضو اصلی خانواده<input className="input" name="familyPhone" inputMode="numeric" pattern="09[0-9]{9}" required/></label>}<label className="label">رمز ثابت<input className="input" type="password" name="password" minLength={6} required/></label>{error&&<div className="error">{error}</div>}<button className="btn" disabled={loading}>{loading?"در حال انجام...":mode==="login"?"ورود":"ثبت‌نام"}</button></form></section></main>}
