"use client";
import { useEffect,useMemo,useState } from "react";
import { BellRing,FileHeart,History,LogOut,MapPin,NotebookPen,Pill,Plus,UserRoundPlus } from "lucide-react";
import { supabaseBrowser } from "@/lib/supabase";
type Profile={id:string;first_name:string};type Elder={relationship:string;custom_relationship:string|null;senior:any};type Tab="home"|"add"|"health"|"remember"|"history"|"notes"|"contacts"|"dates";
const relations=["مامان","بابا","مامان بزرگ","بابا بزرگ","خاله","دایی","عمه","عمو","سایر"];
export function FamilyDashboard({profile,onLogout}:{profile:Profile;onLogout:()=>void}){const sb=useMemo(()=>supabaseBrowser(),[]);const [elders,setElders]=useState<Elder[]>([]);const [selected,setSelected]=useState<any>(null);const [tab,setTab]=useState<Tab>("home");const [checkins,setCheckins]=useState<any[]>([]);const [outings,setOutings]=useState<any[]>([]);const [notifications,setNotifications]=useState<any[]>([]);const [due,setDue]=useState<any[]>([]);const [location,setLocation]=useState<any>(null);const [service,setService]=useState<any>(null);const [error,setError]=useState("");
 async function token(){return (await sb.auth.getSession()).data.session?.access_token}
 async function loadElders(){const {data}=await sb.from("care_links").select("relationship,custom_relationship,senior:profiles!care_links_senior_id_fkey(*)").eq("family_id",profile.id);const list=(data??[]) as unknown as Elder[];setElders(list);if(!selected&&list[0])setSelected(list[0].senior)}
 async function loadData(){if(!selected)return;const [{data:c},{data:o},{data:n},{data:a},{data:d},{data:l},{data:s}]=await Promise.all([sb.from("checkins").select("*").eq("senior_id",selected.id).order("submitted_at",{ascending:false}).limit(30),sb.from("outings").select("*").eq("senior_id",selected.id).order("left_at",{ascending:false}).limit(30),sb.from("notifications").select("*").eq("recipient_id",profile.id).order("created_at",{ascending:false}).limit(30),sb.from("appointments").select("*").eq("senior_id",selected.id).is("completed_at",null),sb.from("special_dates").select("*").eq("senior_id",selected.id),sb.from("location_responses").select("*").eq("senior_id",selected.id).order("created_at",{ascending:false}).limit(1).maybeSingle(),sb.from("service_requests").select("*").eq("senior_id",selected.id).order("created_at",{ascending:false}).limit(1).maybeSingle()]);setCheckins(c??[]);setOutings(o??[]);setNotifications(n??[]);setLocation(l);setService(s);const now=Date.now();const reminders:any[]=[];(a??[]).forEach((x:any)=>{const min=(new Date(x.starts_at).getTime()-now)/60000;if(min<=10080&&min>0)reminders.push({id:`a-${x.id}`,title:"یادآوری ویزیت",body:`${x.title}؛ ${min<=60?"کمتر از یک ساعت":min<=180?"کمتر از سه ساعت":min<=1440?"فردا":"کمتر از یک هفته"} مانده است.`});if(min<=0&&min>-1440)reminders.push({id:`r-${x.id}`,title:"ثبت گزارش ویزیت",body:"در صورت تمایل اطلاعات و گزارش ویزیت را در پرونده پزشکی ثبت کنید."})});(d??[]).forEach((x:any)=>{const base=new Date(x.event_date);let next=new Date(new Date().getFullYear(),base.getMonth(),base.getDate());if(next.getTime()<now)next=new Date(next.getFullYear()+1,next.getMonth(),next.getDate());const days=Math.ceil((next.getTime()-now)/86400000);if([30,7,1,0].some(k=>days<=k)&&days<=30)reminders.push({id:`d-${x.id}`,title:x.occasion,body:days===0?"امروز است.":`${days} روز تا این تاریخ مانده است.`})});setDue(reminders)}useEffect(()=>{void loadElders()},[]);useEffect(()=>{void loadData()},[selected]);
 async function link(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const res=await fetch("/api/link-senior",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${await token()}`},body:JSON.stringify({code:f.get("code"),relationship:f.get("relationship"),customRelationship:f.get("customRelationship")})});const j=await res.json();if(!res.ok)setError(j.message);else{setTab("home");await loadElders()}}
 async function acknowledge(c:any){const msg=prompt("پیام اختیاری برای سالمند:","")||null;const update:any={acknowledged_at:new Date().toISOString(),family_message:msg};if(c.concern_level==="needs_call"){update.call_status=confirm("تماس انجام شده است؟ اگر لغو را بزنید، زمان تماس بعدی ثبت می‌شود.")?"done":"later";if(update.call_status==="later")update.call_at=prompt("زمان دقیق تماس؛ مانند 2026-09-01T18:30")||null}await sb.from("checkins").update(update).eq("id",c.id);await sb.from("notifications").insert({recipient_id:selected.id,senior_id:selected.id,type:"family_ack",title:"پیام خانواده",body:msg||`${elders.find(e=>e.senior.id===selected.id)?.custom_relationship||elders.find(e=>e.senior.id===selected.id)?.relationship||"عزیزم"} عزیزم، پیغامت رو دیدم.`});await loadData()}
 async function requestLocation(o:any){const {data:r}=await sb.from("location_requests").insert({senior_id:selected.id,family_id:profile.id,outing_id:o.id,status:"pending"}).select().single();if(r)await sb.from("outings").update({location_request_id:r.id}).eq("id",o.id);await loadData()}
 async function extendOuting(o:any){const time=prompt("زمان بازگشت جدید به شکل ساعت:دقیقه، مانند 21:30");if(!time)return;const date=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tehran"}).format(new Date());await sb.from("outings").update({expected_return_at:`${date}T${time}:00+03:30`,extension_count:(o.extension_count||0)+1}).eq("id",o.id);await loadData()}
 async function arrangeService(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!service)return;const f=new FormData(e.currentTarget);await sb.from("service_requests").update({status:"arranged",driver_name:f.get("driver")||null,vehicle:f.get("vehicle")||null,plate:f.get("plate")||null,eta:f.get("eta")||null}).eq("id",service.id);await loadData()}
 async function closeEmergency(id:string){const result=prompt("نتیجه پیگیری اختیاری:","")||null;await sb.from("emergencies").update({status:"closed",closed_at:new Date().toISOString(),followup_result:result}).eq("id",id)}
 async function resetPassword(){const password=prompt("رمز جدید سالمند (حداقل ۶ کاراکتر):");if(!password)return;const res=await fetch("/api/reset-senior-password",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${await token()}`},body:JSON.stringify({seniorId:selected.id,password})});const j=await res.json();alert(res.ok?"رمز تغییر کرد.":j.message)}
 async function disconnect(){if(!confirm("اتصال این سالمند قطع شود؟ اطلاعات او حذف نمی‌شود."))return;const res=await fetch("/api/disconnect",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${await token()}`},body:JSON.stringify({seniorId:selected.id})});if(res.ok){setSelected(null);await loadElders()}}
 return <main className="shell"><header className="row between"><div><div className="brand">هملی | همراه بیمار</div><b>{profile.first_name} عزیز</b></div><button className="btn secondary" onClick={onLogout}><LogOut/></button></header>{error&&<div className="error">{error}</div>}<div className="tabs" style={{marginTop:18}}><button className={`tab ${tab==="home"?"active":""}`} onClick={()=>setTab("home")}>داشبورد</button><button className={`tab ${tab==="add"?"active":""}`} onClick={()=>setTab("add")}><Plus/> افزودن سالمند</button><button className={`tab ${tab==="health"?"active":""}`} onClick={()=>setTab("health")}>اطلاعات سالمند</button><button className={`tab ${tab==="remember"?"active":""}`} onClick={()=>setTab("remember")}>یادت باشه</button><button className={`tab ${tab==="history"?"active":""}`} onClick={()=>setTab("history")}>تاریخچه</button><button className={`tab ${tab==="notes"?"active":""}`} onClick={()=>setTab("notes")}>یادداشت</button></div>
 {elders.length>0&&<div className="tabs" style={{marginTop:12}}>{elders.map(e=><button className={`tab ${selected?.id===e.senior.id?"active":""}`} key={e.senior.id} onClick={()=>setSelected(e.senior)}>{e.senior.first_name} ({e.custom_relationship||e.relationship})</button>)}</div>}
 {tab==="add"&&<form className="card stack" onSubmit={link} style={{marginTop:18}}><h2>افزودن سالمند</h2><label className="label">کد اتصال<input className="input" name="code" required/></label><label className="label">نسبت<select className="input" name="relationship">{relations.map(x=><option key={x}>{x}</option>)}</select></label><label className="label">اگر سایر است، نسبت را بنویسید<input className="input" name="customRelationship"/></label><button className="btn">اتصال حساب</button></form>}
 {tab==="home"&&!selected&&<div className="card" style={{marginTop:18}}>ابتدا سالمند را با کد اتصال اضافه کنید.</div>}
 {tab==="home"&&selected&&<div className="stack" style={{marginTop:18}}><section className="card"><div className="row between"><div><b style={{fontSize:22}}>{selected.first_name} {selected.last_name}</b><p className="muted">آخرین وضعیت و فعالیت</p></div><div className="stack"><button className="btn secondary" onClick={resetPassword}>بازنشانی رمز</button><button className="btn danger" onClick={disconnect}>قطع اتصال</button></div></div>{checkins[0]?<div className="notice"><b>{checkins[0].feeling==="good"?"خوبم":checkins[0].feeling==="okay"?"معمولی‌ام":"خوب نیستم"}</b><p>{checkins[0].acknowledged_at?"تأیید شده":"در انتظار تأیید شما"}</p>{!checkins[0].acknowledged_at&&<button className="btn" onClick={()=>acknowledge(checkins[0])}>دیدم و تأیید می‌کنم</button>}</div>:<p className="muted">هنوز وضعیتی ثبت نشده است.</p>}</section>
 <section><h2 className="sectionTitle">هشدارها و پیام‌ها</h2><div className="list">{[...due,...notifications].map(n=><article className="listItem" key={n.id}><b>{n.title}</b><p>{n.body}</p>{"read_at" in n&&!n.read_at&&<button className="btn secondary" onClick={async()=>{await sb.from("notifications").update({read_at:new Date().toISOString()}).eq("id",n.id);await loadData()}}>تأیید پیام</button>}</article>)}</div></section>
 <section className="card stack"><h2>وضعیت خروج</h2>{outings[0]&&!outings[0].returned_at?<><p>{selected.first_name} خارج از خانه است؛ مقصد: {outings[0].destination}</p><div className="grid2"><button className="btn secondary" onClick={()=>requestLocation(outings[0])}><MapPin/> درخواست موقعیت</button><a className="btn" style={{textAlign:"center",textDecoration:"none"}} href={`tel:${selected.phone}`}>تماس</a><button className="btn green" onClick={()=>extendOuting(outings[0])}>تمدید زمان</button></div>{location?.response==="shared"&&location.latitude&&<a target="_blank" rel="noreferrer" href={`https://www.google.com/maps?q=${location.latitude},${location.longitude}`}>مشاهده آخرین موقعیت ارسالی</a>}{location?.response==="safe_on_time"&&<div className="success">اعلام کرده است جای نگرانی نیست و سر ساعت برمی‌گردد.</div>}</>:<p className="muted">در حال حاضر در خانه است.</p>}</section>
 {service?.status==="requested"&&<form className="card stack" onSubmit={arrangeService}><h2>درخواست خودرو</h2><p className="muted">تمام اطلاعات زیر اختیاری است.</p><Field name="driver" label="نام راننده"/><Field name="vehicle" label="خودرو"/><Field name="plate" label="پلاک"/><Field name="eta" label="زمان تقریبی رسیدن"/><button className="btn">ثبت اطلاعات خودرو</button></form>}
 <div className="grid2"><button className="service" onClick={()=>setTab("health")}><FileHeart/> اطلاعات سالمند</button><button className="service" onClick={()=>setTab("remember")}><BellRing/> یادت باشه</button><button className="service" onClick={()=>setTab("notes")}><NotebookPen/> یادداشت</button><button className="service" onClick={()=>setTab("history")}><History/> تاریخچه</button></div></div>}
 {selected&&tab==="health"&&<HealthPanel senior={selected} sb={sb}/>} {selected&&tab==="remember"&&<RememberPanel senior={selected} sb={sb}/>} {selected&&tab==="notes"&&<NotesPanel senior={selected} sb={sb}/>} {selected&&tab==="history"&&<HistoryPanel checkins={checkins} outings={outings} acknowledge={acknowledge}/>} </main>}

function FormBox({title,children,onSubmit}:{title:string;children:React.ReactNode;onSubmit:(f:FormData)=>Promise<void>}){return <form className="card stack" onSubmit={async e=>{e.preventDefault();await onSubmit(new FormData(e.currentTarget));e.currentTarget.reset()}}><h3>{title}</h3>{children}<button className="btn">ثبت</button></form>}
const Field=({name,label,type="text",required=false}:{name:string;label:string;type?:string;required?:boolean})=><label className="label">{label}<input className="input" name={name} type={type} required={required}/></label>;
function HealthPanel({senior,sb}:{senior:any;sb:any}){const [section,setSection]=useState("medicine");const save=(table:string,make:(f:FormData)=>any)=>async(f:FormData)=>{const {error}=await sb.from(table).insert({senior_id:senior.id,...make(f)});if(error)alert(error.message)};async function saveRecord(f:FormData){const {data,error}=await sb.from("health_records").insert({senior_id:senior.id,title:f.get("title"),record_type:f.get("type"),condition_summary:f.get("summary"),symptoms:f.get("symptoms"),diagnosis:f.get("diagnosis"),treatment:f.get("treatment"),physician_name:f.get("doctor"),record_date:f.get("date")||null,notes:f.get("notes")}).select().single();if(error){alert(error.message);return}const file=f.get("file") as File;if(file&&file.size){const path=`${senior.id}/${crypto.randomUUID()}-${file.name}`;const up=await sb.storage.from("medical-files").upload(path,file);if(up.error){alert(up.error.message);return}await sb.from("medical_files").insert({senior_id:senior.id,health_record_id:data.id,storage_path:path,file_name:file.name,content_type:file.type})}}return <section className="stack" style={{marginTop:18}}><div className="tabs">{[["medicine","داروها"],["record","گزارش پزشکی"],["visit","ویزیت‌ها"],["contact","مخاطبین پزشکی"],["date","تاریخ‌های خاص"]].map(([k,l])=><button className={`tab ${section===k?"active":""}`} onClick={()=>setSection(k)} key={k}>{l}</button>)}</div>
 {section==="medicine"&&<FormBox title="ثبت دارو" onSubmit={save("medicines",f=>({medicine_name:f.get("name"),dosage:f.get("dosage"),times_of_day:String(f.get("times")).split(","),days_of_week:String(f.get("days")).split(","),is_daily:f.get("daily")==="on",course_start:f.get("start")||null,course_end:f.get("end")||null,notes:f.get("notes")}))}><Field name="name" label="نام دارو" required/><Field name="dosage" label="مقدار مصرف"/><Field name="times" label="ساعت‌ها؛ با کاما جدا شود"/><Field name="days" label="روزهای هفته؛ با کاما جدا شود"/><label><input type="checkbox" name="daily"/> هر روز</label><div className="grid2"><Field name="start" label="شروع دوره" type="date"/><Field name="end" label="پایان دوره" type="date"/></div><Field name="notes" label="توضیحات مانند بعد از غذا"/></FormBox>}
 {section==="record"&&<FormBox title="پرونده و گزارش پزشکی" onSubmit={saveRecord}><Field name="title" label="عنوان" required/><Field name="type" label="نوع گزارش یا شرایط"/><Field name="summary" label="شرح شرایط سالمند"/><Field name="symptoms" label="علائم"/><Field name="diagnosis" label="تشخیص"/><Field name="treatment" label="درمان"/><Field name="doctor" label="پزشک"/><Field name="date" label="تاریخ" type="date"/><Field name="notes" label="توضیحات"/><label className="label">بارگذاری گزارش، تصویر یا PDF<input className="input" name="file" type="file" accept="image/*,.pdf"/></label></FormBox>}
 {section==="visit"&&<FormBox title="ثبت ویزیت بعدی" onSubmit={save("appointments",f=>({title:f.get("title"),doctor_name:f.get("doctor"),clinic_name:f.get("clinic"),starts_at:f.get("starts"),notes:f.get("notes")}))}><Field name="title" label="عنوان ویزیت" required/><Field name="doctor" label="پزشک"/><Field name="clinic" label="مطب یا مرکز"/><Field name="starts" label="تاریخ و ساعت" type="datetime-local" required/><Field name="notes" label="توضیحات"/></FormBox>}
 {section==="contact"&&<FormBox title="ثبت مخاطب پزشکی" onSubmit={save("medical_contacts",f=>({name:f.get("name"),contact_type:f.get("type"),phone:f.get("phone"),address:f.get("address"),notes:f.get("notes")}))}><Field name="name" label="نام" required/><Field name="type" label="پزشک، مطب، پرستار و..."/><Field name="phone" label="شماره تماس"/><Field name="address" label="آدرس"/><Field name="notes" label="توضیحات"/></FormBox>}
 {section==="date"&&<FormBox title="تاریخ خاص" onSubmit={save("special_dates",f=>({occasion:f.get("occasion"),event_date:f.get("date"),notes:f.get("notes")}))}><Field name="occasion" label="مناسبت" required/><Field name="date" label="تاریخ اصلی" type="date" required/><Field name="notes" label="توضیحات"/></FormBox>}</section>}
function RememberPanel({senior,sb}:{senior:any;sb:any}){const [items,setItems]=useState<any[]>([]);async function load(){const {data}=await sb.from("remember_messages").select("*").eq("senior_id",senior.id).order("created_at",{ascending:false});setItems(data??[])}useEffect(()=>{void load()},[senior.id]);return <section className="stack" style={{marginTop:18}}><FormBox title="ارسال پیام یادت باشه" onSubmit={async f=>{const {error}=await sb.from("remember_messages").insert({senior_id:senior.id,family_id:(await sb.auth.getUser()).data.user.id,title:f.get("title"),body:f.get("body")});if(error)alert(error.message);else await load()}}><Field name="title" label="عنوان" required/><label className="label">متن<textarea className="input" name="body" required/></label></FormBox><div className="list">{items.map(x=><article className="listItem" key={x.id}><b>{x.title}</b><p>{x.body}</p><small className="muted">{x.read_at?`خوانده‌شده | پاسخ: ${x.quick_response||"بدون پاسخ"}`:"خوانده‌نشده"}</small>{!x.read_at&&<button className="btn secondary" onClick={async()=>{const title=prompt("عنوان",x.title);const body=prompt("متن",x.body);if(title&&body){await sb.from("remember_messages").update({title,body,updated_at:new Date().toISOString()}).eq("id",x.id);await load()}}}>ویرایش قبل از دیده‌شدن</button>}</article>)}</div></section>}
function NotesPanel({senior,sb}:{senior:any;sb:any}){return <section style={{marginTop:18}}><FormBox title="یادداشت خانواده" onSubmit={async f=>{await sb.from("family_notes").insert({senior_id:senior.id,family_id:(await sb.auth.getUser()).data.user.id,title:f.get("title"),body:f.get("body"),remind_at:f.get("remind")||null})}}><Field name="title" label="عنوان" required/><label className="label">متن<textarea className="input" name="body" required/></label><Field name="remind" label="یادآوری اختیاری" type="datetime-local"/></FormBox></section>}
function HistoryPanel({checkins,outings,acknowledge}:{checkins:any[];outings:any[];acknowledge:(x:any)=>void}){const [kind,setKind]=useState("status");return <section className="stack" style={{marginTop:18}}><div className="tabs"><button className={`tab ${kind==="status"?"active":""}`} onClick={()=>setKind("status")}>تاریخچه وضعیت</button><button className={`tab ${kind==="outing"?"active":""}`} onClick={()=>setKind("outing")}>تاریخچه رفت‌وآمد</button></div><div className="list">{(kind==="status"?checkins:outings).map(r=><article className="listItem" key={r.id}><b>{kind==="status"?`${r.local_date} | ${r.slot} | ${r.feeling}`:`${r.destination} | ${new Date(r.left_at).toLocaleString("fa-IR")}`}</b>{kind==="status"&&!r.acknowledged_at&&<button className="btn secondary" onClick={()=>acknowledge(r)}>تأیید</button>}</article>)}</div></section>}
