"use client";
import { useEffect,useMemo,useState } from "react";
import { BellRing,CarFront,LogOut,MapPin,PhoneCall,RefreshCw} from "lucide-react";
import { supabaseBrowser } from "@/lib/supabase";

type Profile={id:string;first_name:string;connection_code:string|null;primary_family_id:string|null};type Tab="home"|"remember";
const slots=[{key:"morning",title:"صبح",time:"۷:۳۰ تا ۱۰:۰۰",start:450,close:600,end:630},{key:"noon",title:"ظهر",time:"۱۲:۰۰ تا ۱۴:۳۰",start:720,close:870,end:900},{key:"evening",title:"شب",time:"۲۰:۰۰ تا ۲۲:۰۰",start:1200,close:1320,end:1350}];
const destinations=["امور پزشکی","امور اداری و بانک","خرید","کافه یا رستوران","دیدن خانواده/ فامیل/ دوست","سایر"];
export function SeniorDashboard({profile,onLogout}:{profile:Profile;onLogout:()=>void}){const sb=useMemo(()=>supabaseBrowser(),[]);const [tab,setTab]=useState<Tab>("home");const [checkins,setCheckins]=useState<any[]>([]);const [messages,setMessages]=useState<any[]>([]);const [notice,setNotice]=useState<any>(null);const [error,setError]=useState("");const [outing,setOuting]=useState<any>(null);const [service,setService]=useState<any>(null);const [refreshing,setRefreshing]=useState(false);
 const today=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tehran",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());const parts=new Intl.DateTimeFormat("en-GB",{timeZone:"Asia/Tehran",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date()).split(":");const minute=Number(parts[0])*60+Number(parts[1]);
 async function load(){const archiveCutoff=new Date(Date.now()-30*86400000).toISOString();const [{data:c},{data:m},{data:o},{data:s}]=await Promise.all([sb.from("checkins").select("*").eq("senior_id",profile.id).eq("local_date",today),sb.from("remember_messages").select("*").eq("senior_id",profile.id).or(`read_at.is.null,read_at.gt.${archiveCutoff}`).order("created_at",{ascending:false}),sb.from("outings").select("*").eq("senior_id",profile.id).is("returned_at",null).maybeSingle(),sb.from("service_requests").select("*").eq("senior_id",profile.id).neq("status","completed").order("created_at",{ascending:false}).limit(1).maybeSingle()]);setCheckins(c??[]);setMessages(m??[]);setOuting(o);setService(s);const {data:n}=await sb.from("notifications").select("*").eq("recipient_id",profile.id).order("created_at",{ascending:false}).limit(1).maybeSingle();setNotice(n)}useEffect(()=>{void load()},[]);
 async function checkin(slot:string,feeling:string){let concern=null;if(feeling==="not_well")concern=prompt("یکی را بنویسید: feels_unwell یا needs_call یا emergency")||"feels_unwell";const {error:e}=await sb.from("checkins").insert({senior_id:profile.id,local_date:today,slot,feeling,concern_level:concern});if(e)setError(e.message);else void load()}
 async function startOuting(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const {error:e2}=await sb.from("outings").insert({senior_id:profile.id,destination:f.get("destination"),destination_note:f.get("note"),expected_return_at:f.get("returnAt")});if(e2)setError(e2.message);else void load()}
 async function requestService(){await sb.from("service_requests").insert({outing_id:outing.id,senior_id:profile.id});await load()}async function locate(kind:"share"|"safe"){if(kind==="safe"){await sb.from("location_responses").insert({request_id:outing.location_request_id,senior_id:profile.id,response:"safe_on_time"});return}navigator.geolocation.getCurrentPosition(async p=>{await sb.from("location_responses").insert({request_id:outing.location_request_id,senior_id:profile.id,response:"shared",latitude:p.coords.latitude,longitude:p.coords.longitude,expires_at:new Date(Date.now()+1800000).toISOString()});await load()},()=>setError("دسترسی موقعیت فعال نیست."))}
 async function finishService(){if(!service)return;await sb.from("service_requests").update({status:"completed"}).eq("id",service.id);await load()}
 async function returned(){navigator.geolocation.getCurrentPosition(async p=>{await sb.from("outings").update({returned_at:new Date().toISOString(),return_latitude:p.coords.latitude,return_longitude:p.coords.longitude}).eq("id",outing.id);await load()},async()=>{await sb.from("outings").update({returned_at:new Date().toISOString()}).eq("id",outing.id);await load()})}
 async function emergency(){await sb.from("emergencies").insert({senior_id:profile.id,status:"open"});await load()}
 async function disconnect(){if(!confirm("اتصال خانواده قطع شود؟ اطلاعات شما باقی می‌ماند."))return;const session=(await sb.auth.getSession()).data.session;if(!session)return;const res=await fetch("/api/disconnect",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${session.access_token}`},body:"{}"});const j=await res.json();if(res.ok)alert(`اتصال قطع شد. کد جدید: ${j.connectionCode}`);else setError(j.message)}
 async function respondMessage(id:string,response:string){await sb.from("remember_messages").update({read_at:new Date().toISOString(),quick_response:response}).eq("id",id);await load()}
 const times=[] as string[];for(let h=0;h<24;h++)for(const m of [0,30])times.push(`${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}`);
 async function refresh(){setRefreshing(true);setError("");await load();setRefreshing(false)}
 const activeReminder=slots.find(s=>minute>=s.start&&minute<=s.close&&!checkins.some(c=>c.slot===s.key));return <main className="shell"><header className="row between"><div><div className="brand">هملی</div><b>{profile.first_name} عزیز، خوش آمدید</b></div><button className="btn secondary" onClick={onLogout} aria-label="خروج"><LogOut/></button></header><button className="btn secondary" style={{width:"100%",marginTop:12}} onClick={refresh} disabled={refreshing}><RefreshCw/> {refreshing?"در حال به‌روزرسانی":"به‌روزرسانی اطلاعات"}</button>{profile.connection_code&&<div className="notice" style={{marginTop:16}}>کد اتصال خانواده: <b style={{fontSize:24}}>{profile.connection_code}</b></div>}{activeReminder&&<div className="notice" style={{marginTop:12}}><b>یادآوری ثبت وضعیت {activeReminder.title}</b><p>{minute>=activeReminder.close-30?"کمتر از ۳۰ دقیقه تا پایان بازه مانده است.":"بازه ثبت وضعیت شروع شده است."}</p></div>}{error&&<div className="error" style={{marginTop:12}}>{error}</div>}
 {tab==="home"&&<div className="stack" style={{marginTop:18}}>{notice?<section className="notice"><b>{notice.title}</b><p>{notice.body}</p></section>:<section className="card"><b>آخرین پیام</b><p className="muted">هنوز پیامی وجود ندارد.</p></section>}<section><h2 className="sectionTitle">ثبت وضعیت امروز</h2><div className="slider">{slots.map(s=>{const rec=checkins.find(c=>c.slot===s.key);const state=rec?"ثبت شده":minute>s.end?"ثبت نشد":minute>=s.start?"در انتظار ثبت":"نوبت بعدی";return <article className={`slide ${minute<s.start?"upcoming":""}`} key={s.key}><div className="row between"><h3>نوبت {s.title}</h3><span className="pill">{state}</span></div><p className="muted">{s.time}</p>{rec?<b>{rec.feeling==="good"?"خوبم":rec.feeling==="okay"?"معمولی‌ام":"خوب نیستم"}</b>:minute>=s.start&&minute<=s.end&&<div className="grid2"><button className="btn green" onClick={()=>checkin(s.key,"good")}>خوبم</button><button className="btn secondary" onClick={()=>checkin(s.key,"okay")}>معمولی‌ام</button><button className="btn danger" onClick={()=>checkin(s.key,"not_well")}>خوب نیستم</button></div>}</article>})}</div></section>
 {!outing?<form className="card stack" onSubmit={startOuting}><div className="row"><span className="icon"><CarFront/></span><h2 className="sectionTitle">می‌روم بیرون</h2></div><label className="label">مقصد<select className="input" name="destination">{destinations.map(x=><option key={x}>{x}</option>)}</select></label><label className="label">توضیح اختیاری<input className="input" name="note"/></label><label className="label">زمان بازگشت<select className="input" name="returnAt">{times.map(x=><option key={x} value={`${today}T${x}:00+03:30`}>{x}</option>)}</select></label><button className="btn">ثبت خروج</button></form>:<section className="card stack"><b>خارج از خانه هستید: {outing.destination}</b>{!service?<button className="btn" onClick={requestService}>برام سرویس بگیر!</button>:<><div className="success">درخواست خودرو برای خانواده ارسال شد.{service.driver_name?` راننده: ${service.driver_name}، خودرو: ${service.vehicle||"-"}، پلاک: ${service.plate||"-"}، رسیدن: ${service.eta||"-"}`:""}</div><button className="btn secondary" onClick={finishService}>اتمام درخواست</button></>}{outing.location_request_id&&<><button className="btn secondary" onClick={()=>locate("share")}><MapPin/> ارسال موقعیت</button><button className="btn green" onClick={()=>locate("safe")}>جای نگرانی نیست، سر ساعت برمی‌گردم</button></>}<button className="btn green" onClick={returned}>برگشتم</button></section>}
 <button className="service" onClick={emergency}><span className="icon" style={{background:"#ffeded",color:"#c63838"}}><PhoneCall/></span><span><b>تماس ضروری</b><small className="muted" style={{display:"block"}}>برای خانواده هشدار فوری بفرستید</small></span></button><button className="service" onClick={()=>setTab("remember")}><span className="icon"><BellRing/></span><span><b>یادت باشه!</b><small className="muted" style={{display:"block"}}>پیام‌های خانواده را بخوانید</small></span></button>{profile.primary_family_id&&<button className="btn danger" onClick={disconnect}>قطع اتصال خانواده</button>}</div>}
 {tab==="remember"&&<Panel title="یادت باشه" back={()=>setTab("home")}><div className="list">{messages.map(m=><article className="listItem" key={m.id}><b>{m.title}</b><p>{m.body}</p>{!m.read_at&&<div className="grid2"><button className="btn green" onClick={()=>respondMessage(m.id,"understood")}>متوجه شدم</button><button className="btn danger" onClick={()=>respondMessage(m.id,"call_me")}>متوجه نشدم؛ تماس بگیر</button></div>}</article>)}</div></Panel>}
 </main>}
function Panel({title,back,children}:{title:string;back:()=>void;children:React.ReactNode}){return <section className="stack" style={{marginTop:18}}><div className="row between"><h1>{title}</h1><button className="btn secondary" onClick={back}>بازگشت</button></div>{children}</section>}
